[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm cache clean --force',
  'npm install --no-optional',
  'npm run build'
]

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader'
]